
import { PageLayout } from "../../components/layout";

export const BigOView = PageLayout(`
    <h1>Big O Visualization</h1>
    <div class="intro-text">
        Visualize how different algorithms perform as the input size (<b>N</b>) grows.
        Notice how <b>O(n²)</b> explodes quickly, while <b>O(log n)</b> stays barely flat!
    </div>

    <div class="visualizer-container" style="flex-direction: column; height: auto; gap: 1rem;">
        
        <!-- Controls -->
        <div style="background: var(--surface-color); padding: 1.5rem; border-radius: 1rem; border: 1px solid var(--glass-border); width: 100%;">
            <label class="form-label" style="display: flex; justify-content: space-between;">
                <span>Input Size (N): <span id="n-display" style="color: var(--primary-color); font-weight: bold;">10</span></span>
                <span style="font-size: 0.8rem; color: var(--subtext-color);">Drag slider to see growth ➔</span>
            </label>
            <input type="range" id="n-slider" min="1" max="50" value="10" step="1" style="width: 100%; accent-color: var(--primary-color);">
        </div>

        <div style="display: flex; gap: 2rem; flex-wrap: wrap;">
            <!-- Chart Area -->
            <div style="flex: 2; min-width: 300px; background: #0f172a; border-radius: 1rem; border: 1px solid var(--glass-border); padding: 1rem; position: relative;">
                <svg id="complexity-chart" viewBox="0 0 600 400" style="width: 100%; height: 100%; overflow: visible;">
                    <!-- Grid Lines -->
                    <line x1="50" y1="350" x2="550" y2="350" stroke="#334155" stroke-width="2" />
                    <line x1="50" y1="50" x2="50" y2="350" stroke="#334155" stroke-width="2" />
                    
                    <!-- Axis Labels -->
                    <text x="550" y="370" fill="var(--subtext-color)" font-size="12" text-anchor="middle">Input (N)</text>
                    <text x="20" y="50" fill="var(--subtext-color)" font-size="12" transform="rotate(-90 20,50)" text-anchor="middle">Time</text>
                    
                    <!-- Curves (Paths will be generated by JS) -->
                    <path id="path-o1" fill="none" stroke="#22c55e" stroke-width="3" />
                    <path id="path-ologn" fill="none" stroke="#eab308" stroke-width="3" />
                    <path id="path-on" fill="none" stroke="#3b82f6" stroke-width="3" />
                    <path id="path-onlogn" fill="none" stroke="#a855f7" stroke-width="3" />
                    <path id="path-on2" fill="none" stroke="#ef4444" stroke-width="3" />
                    
                    <!-- Current N Line -->
                    <line id="current-n-line" x1="50" y1="50" x2="50" y2="350" stroke="white" stroke-width="1" stroke-dasharray="5,5" opacity="0.5" />
                </svg>
            </div>

            <!-- Legend / Live Stats -->
            <div style="flex: 1; min-width: 250px; display: flex; flex-direction: column; gap: 1rem;">
                
                <div class="stat-card" style="border-left: 4px solid #22c55e; background: var(--surface-color); padding: 1rem; border-radius: 0.5rem;">
                    <div style="color: #22c55e; font-weight: bold; font-size: 1.1rem;">O(1) - Constant</div>
                    <div style="color: var(--subtext-color); font-size: 0.9rem;">ops: <span id="val-o1" style="color: white;">1</span></div>
                </div>

                <div class="stat-card" style="border-left: 4px solid #eab308; background: var(--surface-color); padding: 1rem; border-radius: 0.5rem;">
                    <div style="color: #eab308; font-weight: bold; font-size: 1.1rem;">O(log n) - Logarithmic</div>
                    <div style="color: var(--subtext-color); font-size: 0.9rem;">ops: <span id="val-ologn" style="color: white;"></span></div>
                </div>

                <div class="stat-card" style="border-left: 4px solid #3b82f6; background: var(--surface-color); padding: 1rem; border-radius: 0.5rem;">
                    <div style="color: #3b82f6; font-weight: bold; font-size: 1.1rem;">O(n) - Linear</div>
                    <div style="color: var(--subtext-color); font-size: 0.9rem;">ops: <span id="val-on" style="color: white;"></span></div>
                </div>

                <div class="stat-card" style="border-left: 4px solid #a855f7; background: var(--surface-color); padding: 1rem; border-radius: 0.5rem;">
                    <div style="color: #a855f7; font-weight: bold; font-size: 1.1rem;">O(n log n) - Linearithmic</div>
                    <div style="color: var(--subtext-color); font-size: 0.9rem;">ops: <span id="val-onlogn" style="color: white;"></span></div>
                </div>

                <div class="stat-card" style="border-left: 4px solid #ef4444; background: var(--surface-color); padding: 1rem; border-radius: 0.5rem;">
                    <div style="color: #ef4444; font-weight: bold; font-size: 1.1rem;">O(n²) - Quadratic</div>
                    <div style="color: var(--subtext-color); font-size: 0.9rem;">ops: <span id="val-on2" style="color: white;"></span></div>
                </div>

            </div>
        </div>
    </div>

    <div class="action-footer">
        <button id="mark-complete-btn" data-id="big-o" class="complete-btn">
            Mark as Completed
        </button>
    </div>
`, 'topic/analysis', 'Back to Analysis');

export function setupBigOVisualization() {
    const slider = document.getElementById('n-slider') as HTMLInputElement;
    const nDisplay = document.getElementById('n-display');
    const nLine = document.getElementById('current-n-line');
    if (!slider || !nDisplay || !nLine) return;

    // SVG scaling params
    const width = 500; // 50 to 550
    const height = 300; // 350 to 50
    const startX = 50;
    const startY = 350;
    const maxN = 50;
    const maxY = 200; // Arbitrary scale factor to keep things visible

    // Helper to map N to X coordinate
    const getX = (n: number) => startX + (n / maxN) * width;

    // Helper to map Value to Y coordinate (inverted)
    const getY = (val: number) => startY - Math.min((val / maxY) * height, height);

    // Generate Path Data
    const generatePath = (fn: (n: number) => number) => {
        let d = `M ${getX(0)} ${getY(fn(0))}`;
        for (let i = 1; i <= maxN; i++) {
            d += ` L ${getX(i)} ${getY(fn(i))}`;
        }
        return d;
    };

    // Draw static paths
    document.getElementById('path-o1')?.setAttribute('d', generatePath(() => 10)); // Constant scaled up a bit
    document.getElementById('path-ologn')?.setAttribute('d', generatePath(n => Math.log2(n || 1) * 10));
    document.getElementById('path-on')?.setAttribute('d', generatePath(n => n * 2));
    document.getElementById('path-onlogn')?.setAttribute('d', generatePath(n => n * Math.log2(n || 1) * 1.5));
    document.getElementById('path-on2')?.setAttribute('d', generatePath(n => (n * n) * 0.15)); // Scaled down to fit

    const update = () => {
        const n = parseInt(slider.value);
        if (nDisplay) nDisplay.textContent = n.toString();

        // Update Line Position
        const currentX = getX(n);
        nLine.setAttribute('x1', currentX.toString());
        nLine.setAttribute('x2', currentX.toString());

        // Update Values
        const updateVal = (id: string, val: number) => {
            const el = document.getElementById(id);
            if (el) el.textContent = Math.round(val).toString();
        };

        updateVal('val-o1', 1);
        updateVal('val-ologn', Math.log2(n));
        updateVal('val-on', n);
        updateVal('val-onlogn', n * Math.log2(n));
        updateVal('val-on2', n * n);
    };

    slider.addEventListener('input', update);
    update(); // Init
}
